### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GoldenSpringFox** [GoldenSpringFox/Intro2cs_Ex10#1]
general
- [x]  fix blue object border collision
- [x]  finish game after x rounds
- [x] create apples, walls, and snake
- [x] check if cell is empty
- [x] snakeless debug mode

snake progress
- [x] moving snake of size 1 
- [x] moving snake of size 3
- [x] wall collision
- [x] body collision
- [x] grow

apple progress
- [x] supporting the game with one apple and no snake
- [x] supporting the game with three apples and no snake
- [x] supporting the game with one apple and the snake
- [x] making the snake eat an apple
- [x] update score

wall progress
- [x] supporting one wall in the game with nothing else
- [x] supporting three walls in the game and nothing else
- [x] supporting the game not crashing when walls go out of bounds
- [x] supporting the snake going into a wall
- [x] supporting the wall going into the snake and cutting him
- [x] supporting a game with the snake apples and a wall
- [x] supporting the wall going over an apple
- [x] makeing sure walls can go over eachother 

finishing touchs
- [x] makeing sure the game can run on -1 rounds
- [x] makeing sure when the game ends the snake gets drawn without an head and the board is drawn one more time
- [x] makeing sure the snake can go to where the tail was last round
- [x] makeing sure that if the snake eats an apple there will be anouther apple in the same round
- [x] if the length of the snake after the wall cuts him is 1 you draw the wall on the snake and end the game
- [x] make presubmit tests pass!!!
